#!/usr/bin/env python3
"""
Classical baseline evaluation on the test folds of a CV experiment.

Runs every learning-free baseline (core/baselines.py: nearest, linear, IDW,
telea, ns) on the TEST split of each fold — exactly the same held-out
environments and exactly the same metrics (core/metrics.py, masked SSIM) as
the learned models, so numbers are directly comparable in one table.

Baselines need no training, therefore this can run at any time after the
experiment directory exists (right after `run_cv_experiment.py --name ...`
prints it), independently of GPU training progress. CPU-parallel.

Usage:
    python run_baselines.py --exp_dir runs/cv_unet_beta05_x
    python run_baselines.py --exp_dir runs/cv_unet_beta05_x --methods nearest idw
    python run_baselines.py --exp_dir runs/cv_unet_beta05_x --folds 0 --workers 16

Outputs (inside the experiment directory):
    baselines/fold_k_<Env>/per_sample_test.csv   one row per sample × method
    baselines/fold_k_<Env>/metrics_test.json     mean/std/n per method
    baselines/summary/baselines_summary.{json,csv}
    baselines/summary/table_baselines.tex        methods (+ model, if evaluated)
                                                 × environments
"""
import argparse
import json
import time
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime
from functools import partial
from pathlib import Path

import numpy as np

from elevcomp.baselines import BASELINES
from elevcomp.utils import aggregate_rows, nanmean, nanstd, write_csv

# Same headline metrics as the model tables (comp metrics are omitted:
# baselines keep observed pixels verbatim, so composite == prediction).
TABLE_METRICS = ['rmse', 'rmse_hole', 'mae', 'mae_hole']

# Readable LaTeX labels for the trained-model reference row (raw config names
# contain underscores that break LaTeX text mode).
MODEL_LABELS = {
    'unet': 'U-Net (custom)',
    'unet_pytorch': 'U-Net (ResNet-34)',
    'attunet': 'Attention U-Net',
    'segformer': 'SegFormer (MiT-B2)',
    'pconv': 'PConv-UNet',
}


def eval_one_file(rel_path: str, data_root: str, methods: list) -> list:
    """Worker: run all baselines on one sample, return per-method metric rows."""
    import torch                          # local import keeps fork startup lean
    torch.set_num_threads(1)
    from elevcomp.metrics import compute_metrics

    src = Path(data_root) / rel_path
    d = np.load(src)
    pe = d['partial_elevation'].astype(np.float32)
    pm = d['partial_mask'].astype(np.float32)
    gt = d['gt_elevation'].astype(np.float32)
    gm = d['gt_mask'].astype(np.float32)

    gt_f = np.where(np.isfinite(gt), gt, 0.0)
    gm_t = torch.from_numpy(gm)[None, None]
    pm_t = torch.from_numpy(pm)[None, None]
    gt_t = torch.from_numpy(gt_f)[None, None]

    parts = Path(rel_path).parts
    coverage = float(pm[gm > 0.5].mean()) if (gm > 0.5).any() else float('nan')

    rows = []
    for name in methods:
        filled = BASELINES[name](pe, pm)
        pred_t = torch.from_numpy(np.nan_to_num(filled).astype(np.float32))[None, None]
        # Metre-space inputs → identity denormalization keeps metrics in metres.
        m = compute_metrics(pred_t, gt_t, gm_t, pm_t, partial_elev=None,
                            denorm_std=1.0, denorm_mean=0.0)
        rows.append({'method': name, 'sample_id': rel_path,
                     'env': parts[0], 'trajectory': parts[1],
                     'coverage': coverage, **m})
    return rows


def write_baseline_table(summary: dict, model_rows: dict, out: Path):
    """LaTeX table: baselines (+ trained model rows) × held-out environments."""
    envs = summary['environments']
    methods = summary['methods']
    for metric in ('rmse_hole', 'rmse'):
        # Gather every row so the best (lowest) value per column can be bolded.
        rows = []  # (label, per-env vals, mean, is_model)
        for name in methods:
            vals = [summary['per_env'][e][name].get(metric, {}).get('mean', float('nan'))
                    for e in envs]
            rows.append((name, vals, nanmean(vals), False))
        for label, per_env in model_rows.items():
            vals = [per_env.get(e, {}).get(metric, {}).get('mean', float('nan'))
                    for e in envs]
            rows.append((label, vals, nanmean(vals), True))
        col_min = [min(r[1][i] for r in rows) for i in range(len(envs))]
        mean_min = min(r[2] for r in rows)

        def _b(v, best):
            return f'\\textbf{{{v:.3f}}}' if best else f'{v:.3f}'

        lines = [
            f'% Auto-generated by run_baselines.py — test {metric.upper()} [m] per '
            f'held-out environment. Best (lowest) per column in bold.',
            '% Baselines fill only unobserved pixels; observed stereo is kept verbatim.',
            r'\begin{tabular}{l' + 'c' * len(envs) + 'c}',
            r'\toprule',
            'Method & ' + ' & '.join(envs) + r' & Mean $\pm$ std \\',
            r'\midrule',
        ]
        inserted = False
        for label, vals, mean, is_model in rows:
            if is_model and not inserted:
                lines.append(r'\midrule')
                inserted = True
            cells = ' & '.join(_b(v, abs(v - col_min[i]) < 1e-6)
                               for i, v in enumerate(vals))
            mcell = _b(mean, abs(mean - mean_min) < 1e-6) + f' $\\pm$ {nanstd(vals):.3f}'
            lines.append(f'{label} & {cells} & {mcell}' + r' \\')
        lines += [r'\bottomrule', r'\end{tabular}']
        (out / f'table_baselines_{metric}.tex').write_text('\n'.join(lines) + '\n')


def main():
    p = argparse.ArgumentParser(
        description='Classical baselines on the test folds of a CV experiment.')
    p.add_argument('--exp_dir', required=True,
                   help='experiment directory created by run_cv_experiment.py')
    p.add_argument('--methods', nargs='+', default=list(BASELINES),
                   choices=list(BASELINES))
    p.add_argument('--folds', type=int, nargs='+',
                   help='subset of folds (default: all)')
    p.add_argument('--workers', type=int, default=16,
                   help='CPU worker processes')
    p.add_argument('--recompute', action='store_true',
                   help='overwrite existing baseline results')
    args = p.parse_args()

    exp_dir = Path(args.exp_dir)
    exp = json.load(open(exp_dir / 'experiment.json'))
    folds = json.load(open(exp_dir / 'folds.json'))
    data_root = exp['cv']['data_root']
    sel = args.folds if args.folds is not None else [f['fold'] for f in folds]

    base_dir = exp_dir / 'baselines'
    base_dir.mkdir(exist_ok=True)

    per_env = {}
    for fd in folds:
        if fd['fold'] not in sel:
            continue
        env = fd['test_env']
        out_dir = base_dir / f'fold_{fd["fold"]}_{env}'
        out_dir.mkdir(exist_ok=True)
        done_file = out_dir / 'baselines_done.json'

        if done_file.exists() and not args.recompute:
            done = json.load(open(done_file))
            if set(args.methods) <= set(done['methods']):
                print(f'fold {fd["fold"]} ({env}): already computed — skipping')
                per_env[env] = json.load(open(out_dir / 'metrics_test.json'))
                continue

        print(f'fold {fd["fold"]} ({env}): {len(fd["test_files"])} test samples, '
              f'methods: {args.methods}')
        t0 = time.time()
        worker = partial(eval_one_file, data_root=data_root, methods=args.methods)
        rows = []
        with ProcessPoolExecutor(max_workers=args.workers) as ex:
            for i, r in enumerate(ex.map(worker, fd['test_files'], chunksize=8)):
                rows.extend(r)
                if (i + 1) % 500 == 0:
                    print(f'  {i + 1}/{len(fd["test_files"])} samples')

        write_csv(out_dir / 'per_sample_test.csv', rows)
        agg = {}
        for name in args.methods:
            sub = [{k: v for k, v in r.items() if isinstance(v, float)}
                   for r in rows if r['method'] == name]
            agg[name] = aggregate_rows(sub)
        with open(out_dir / 'metrics_test.json', 'w') as f:
            json.dump(agg, f, indent=2)
        with open(done_file, 'w') as f:
            json.dump({'methods': args.methods,
                       'n_samples': len(fd['test_files']),
                       'wall_time_s': time.time() - t0,
                       'finished_at': datetime.now().isoformat(timespec='seconds')},
                      f, indent=2)
        per_env[env] = agg
        for name in args.methods:
            print(f'  {name:<8} rmse {agg[name]["rmse"]["mean"]:.3f} m | '
                  f'rmse_hole {agg[name].get("rmse_hole", {}).get("mean", float("nan")):.3f} m '
                  f'({time.time() - t0:.0f}s total)')

    if not per_env:
        return

    # ── Cross-environment summary + table ────────────────────────────────────
    sum_dir = base_dir / 'summary'
    sum_dir.mkdir(exist_ok=True)
    envs = sorted(per_env)
    summary = {
        'generated_at': datetime.now().isoformat(timespec='seconds'),
        'methods': args.methods,
        'environments': envs,
        'per_env': per_env,
        'cross_env': {
            name: {m: {'mean': nanmean([per_env[e][name].get(m, {}).get('mean', np.nan)
                                        for e in envs]),
                       'std': nanstd([per_env[e][name].get(m, {}).get('mean', np.nan)
                                      for e in envs])}
                   for m in TABLE_METRICS}
            for name in args.methods},
    }
    with open(sum_dir / 'baselines_summary.json', 'w') as f:
        json.dump(summary, f, indent=2)

    csv_rows = [{'method': name, 'env': e,
                 **{m: per_env[e][name].get(m, {}).get('mean') for m in TABLE_METRICS}}
                for name in args.methods for e in envs]
    write_csv(sum_dir / 'baselines_summary.csv', csv_rows)

    # Include the trained model as a reference row when fold evals exist.
    model_rows = {}
    model_name = exp['config'].get('model', 'model')
    model_label = MODEL_LABELS.get(model_name, model_name.replace('_', r'\_'))
    for fd in folds:
        ev = exp_dir / f'fold_{fd["fold"]}_{fd["test_env"]}' / 'eval' / 'metrics_test.json'
        if ev.exists():
            model_rows.setdefault(f'{model_label} (ours)', {})[fd['test_env']] = \
                json.load(open(ev))['nll']
    write_baseline_table(summary, model_rows, sum_dir)

    print(f'\nSummary → {sum_dir}')
    for name in args.methods:
        c = summary['cross_env'][name]
        print(f'  {name:<8} rmse {c["rmse"]["mean"]:.3f} ± {c["rmse"]["std"]:.3f} m | '
              f'rmse_hole {c["rmse_hole"]["mean"]:.3f} ± {c["rmse_hole"]["std"]:.3f} m')


if __name__ == '__main__':
    main()
